# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  schedule:
    # Run every month the 20th when the clock is 13:00 UTC
    - cron: '0 13 20 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [ '1.6.x', 'stable', 'devel' ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    name: Nim ${{ matrix.nim }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      - run: nimble install -Y
      - run: nimble testDeps -Y
      - run: nimble test
